#!/bin/bash

# Usage open-repo-on-github [REPO] [SHA]

set -x

REPO=$1
SHA=$2

if [[ ! -z $REPO ]]; then
    pushd .
    cd $REPO
fi

ORIGIN=`git config --get remote.origin.url`
ORIGIN=${ORIGIN%.git}
ORIGIN=${ORIGIN#git@github.com:}


if [[ -z $SHA ]]; then
    open https://github.com/${ORIGIN}
else
    open https://github.com/${ORIGIN}/commit/$SHA
fi

if [[ ! -z $REPO ]]; then
    popd
fi
