#!/bin/bash

# Usage open-repo-on-github [REPO] [SHA]

set -x

REPO=$1
SHA=$2

if [[ ! -z $REPO ]]; then
    pushd .
    cd $REPO
fi

bash -lc "/usr/local/bin/gh browse commits/$SHA"

if [[ ! -z $REPO ]]; then
    popd
fi
